const { JSDOM } = require('jsdom');

function $c(html):string {
    let $ = new JSDOM();
    var div = $.window.document.createElement('div');
    div.innerHTML = html;
    return div.innerHTML;
}

module.exports = {
    find_doc: function(doc:string):string { /** Encontrar el documento */
        doc = doc.match(/doc: {([\s\S]*)}/)[1];
        return doc;
    },

    close_doc: function(doc:string):string { /** Encapsular contenido del documento en body tags */
        let doc_content = doc.match(/doc: {([\s\S]*)}/)[1];;
        doc = doc.split(`doc: {${doc_content}}`).join(`<body>${doc_content}</body>`);
        doc = doc.split(`doc:{${doc_content}}`).join(`<body>${doc_content}</body>`);
        return doc;
    },

    tags: function(code:string):string { /** Interpretación: { Nue } --> <Html> */
        let html:string = this.find_doc(code);
        let old_html:string = html;

        html = html.replace(/#!/g,'<!--');
        html = html.replace(/ ?!#/g,'-->');
        html = html.replace(/\ba: ?/g,'<a>');
        html = html.replace(/ ?!a/g,'</a>');
        html = html.replace(/\babbr: ?/g,'<abbr>');
        html = html.replace(/ ?!abbr/g,'</abbr>');
        html = html.replace(/\baddress: ?/g,'<address>');
        html = html.replace(/ ?!address/g,'</address>');
        html = html.replace(/\barea: ?/g,'<area>');
        html = html.replace(/\barticle: ?/g,'<article>');
        html = html.replace(/ ?!article/g,'<!article>');
        html = html.replace(/\baside: ?/g,'<aside>');
        html = html.replace(/ ?!aside/g,'</aside>');
        html = html.replace(/\baudio: ?/g,'<audio>');
        html = html.replace(/ ?!audio/g,'</audio>');
        html = html.replace(/\bbold: ?/g,'<b>');
        html = html.replace(/ ?!bold/g,'</b>');
        html = html.replace(/\bbase: ?/g,'<base>');
        html = html.replace(/\bbdi: ?/g,'<bdi>');
        html = html.replace(/ ?!bdi/g,'</bdi>');
        html = html.replace(/\bbdo: ?/g,'<bdo>');
        html = html.replace(/ ?!bdo/g,'</bdo>');
        html = html.replace(/\bquote: ?/g,'<blockquote>');
        html = html.replace(/ ?!quote/g,'</blockquote>');
        html = html.replace(/br\./g,'<br>');
        html = html.replace(/\bbtn: ?/g,'<button>');
        html = html.replace(/ ?!btn/g,'</button>');
        html = html.replace(/\bcanvas: ?/g,'<canvas>');
        html = html.replace(/ ?!canvas/g,'</canvas>');
        html = html.replace(/\bcaption: ?/g,'<caption>');
        html = html.replace(/ ?!caption/g,'</caption>');
        html = html.replace(/\bcite: ?/g,'<cite>');
        html = html.replace(/ ?!cite/g,'</cite>');
        html = html.replace(/\bcode: ?/g,'<code>');
        html = html.replace(/ ?!code/g,'</code>');
        html = html.replace(/\bcol: ?/g,'<col>');
        html = html.replace(/\bcolgroup: ?/g,'<colgroup>');
        html = html.replace(/ ?!colgroup/g,'</colgroup>');
        html = html.replace(/command/g,'<command>');
        html = html.replace(/\bdatalist: ?/g,'<datalist>');
        html = html.replace(/ ?!datalist/g,'</datalist>');
        html = html.replace(/\bdd: ?/g,'<dd>');
        html = html.replace(/ ?!dd/g,'</dd>');
        html = html.replace(/\bdel: ?/g,'<del>');
        html = html.replace(/ ?!del/g,'</del>');
        html = html.replace(/\bdetails: ?/g,'<details>');
        html = html.replace(/ ?!details/g,'</details>');
        html = html.replace(/\bdfn: ?/g,'<dfn>');
        html = html.replace(/ ?!dfn/g,'</dfn>');
        html = html.replace(/\bdialog: ?/g,'<dialog>');
        html = html.replace(/ ?!dialog/g,'</dialog>');
        html = html.replace(/\bbox: ?/g,'<div>');
        html = html.replace(/ ?!box/g,'</div>');
        html = html.replace(/\btemplate: ?/g,'<div>');
        html = html.replace(/ ?!template/g,'</div>');
        html = html.replace(/\bdl: ?/g,'<dl>');
        html = html.replace(/ ?!dl/g,'</dl>');
        html = html.replace(/\bdt: ?/g,'<dt>');
        html = html.replace(/ ?!dt/g,'</dt>');
        html = html.replace(/\bem: ?/g,'<em>');
        html = html.replace(/ ?!em/g,'</em>');
        html = html.replace(/embed/g,'<embed>');
        html = html.replace(/\bfieldset: ?/g,'<fieldset>');
        html = html.replace(/ ?!fieldset/g,'</fieldset>');
        html = html.replace(/\bfigcaption: ?/g,'<figcaption>');
        html = html.replace(/ ?!figcaption/g,'</figcaption>');
        html = html.replace(/\bfigure: ?/g,'<figure>');
        html = html.replace(/ ?!figure/g,'</figure>');
        html = html.replace(/\bform: ?/g,'<form>');
        html = html.replace(/ ?!form/g,'</form>');
        html = html.replace(/\bh1: ?/g,'<h1>');
        html = html.replace(/ ?!h1/g,'</h1>');
        html = html.replace(/\bh2: ?/g,'<h2>');
        html = html.replace(/ ?!h2/g,'</h2>');
        html = html.replace(/\bh3: ?/g,'<h3>');
        html = html.replace(/ ?!h3/g,'</h3>');
        html = html.replace(/\bh4: ?/g,'<h4>');
        html = html.replace(/ ?!h4/g,'</h4>');
        html = html.replace(/\bh5: ?/g,'<h5>');
        html = html.replace(/ ?!h5/g,'</h5>');
        html = html.replace(/\bh6: ?/g,'<h6>');
        html = html.replace(/ ?!h6/g,'</h6>');
        html = html.replace(/\bheader: ?/g,'<header>');
        html = html.replace(/ ?!header/g,'</header>');
        html = html.replace(/\bhgroup: ?/g,'<hgroup>');
        html = html.replace(/ ?!hgroup/g,'</hgroup>');
        html = html.replace(/\bhr: ?/g,'<hr>');
        html = html.replace(/\bitalic: ?/g,'<i>');
        html = html.replace(/ ?!italic/g,'</i>');
        html = html.replace(/\biframe: ?/g,'<iframe>');
        html = html.replace(/ ?!iframe/g,'</iframe>');
        html = html.replace(/input/g,'<input>');
        html = html.replace(/\bins: ?/g,'<ins>');
        html = html.replace(/ ?!ins/g,'</ins>');
        html = html.replace(/\bkbd: ?/g,'<kbd>');
        html = html.replace(/ ?!kbd/g,'</kbd>');
        html = html.replace(/keygen/g,'<keygen>');
        html = html.replace(/\blabel: ?/g,'<label>');
        html = html.replace(/ ?!label/g,'</label>');
        html = html.replace(/\blegend: ?/g,'<legend>');
        html = html.replace(/ ?!legend/g,'</legend>');
        html = html.replace(/\bli: ?/g,'<li>');
        html = html.replace(/ ?!li/g,'</li>');
        html = html.replace(/\bresource: ?/g,'<resource>');
        html = html.replace(/\bmap: ?/g,'<map>');
        html = html.replace(/ ?!map/g,'</map>');
        html = html.replace(/\bmark: ?/g,'<mark>');
        html = html.replace(/ ?!mark/g,'</mark>');
        html = html.replace(/\bmenu: ?/g,'<menu>');
        html = html.replace(/ ?!menu/g,'</menu>');
        html = html.replace(/\bmeter: ?/g,'<meter>');
        html = html.replace(/ ?!meter/g,'</meter>');
        html = html.replace(/\bnav: ?/g,'<nav>');
        html = html.replace(/ ?!nav/g,'</nav>');
        html = html.replace(/\bnoscript: ?/g,'<noscript>');
        html = html.replace(/ ?!noscript/g,'</noscript>');
        html = html.replace(/\bobject: ?/g,'<object>');
        html = html.replace(/ ?!object/g,'</object>');
        html = html.replace(/\bol: ?/g,'<ol>');
        html = html.replace(/ ?!ol/g,'</ol>');
        html = html.replace(/\boptgroup: ?/g,'<optgroup>');
        html = html.replace(/ ?!optgroup/g,'</optgroup>');
        html = html.replace(/\boption: ?/g,'<option>');
        html = html.replace(/ ?!option/g,'</option>');
        html = html.replace(/\boutput: ?/g,'<output>');
        html = html.replace(/ ?!output/g,'</output>');
        html = html.replace(/\bp: ?/g,'<p>');
        html = html.replace(/ ?!p/g,'</p>');
        html = html.replace(/\bpre: ?/g,'<pre>');
        html = html.replace(/ ?!pre/g,'</pre>');
        html = html.replace(/\bprogress: ?/g,'<progress>');
        html = html.replace(/ ?!progress/g,'</progress>');
        html = html.replace(/\bq: ?/g,'<q>');
        html = html.replace(/ ?!q/g,'</q>');
        html = html.replace(/\brp: ?/g,'<rp>');
        html = html.replace(/ ?!rp/g,'</rp>');
        html = html.replace(/\brt: ?/g,'<rt>');
        html = html.replace(/ ?!rt/g,'</rt>');
        html = html.replace(/\bruby: ?/g,'<ruby>');
        html = html.replace(/ ?!ruby/g,'</ruby>');
        html = html.replace(/\bsamp: ?/g,'<samp>');
        html = html.replace(/ ?!samp/g,'</samp>');
        html = html.replace(/\bjs: ?/g,'<script>');
        html = html.replace(/ ?!js/g,'</script>');
        html = html.replace(/\bsection: ?/g,'<section>');
        html = html.replace(/ ?!section/g,'</section>');
        html = html.replace(/\bselect: ?/g,'<select>');
        html = html.replace(/ ?!select/g,'</select>');
        html = html.replace(/\bsmall: ?/g,'<small>');
        html = html.replace(/ ?!small/g,'</small>');
        html = html.replace(/source/g,'<source>');
        html = html.replace(/\bspan: ?/g,'<span>');
        html = html.replace(/ ?!span/g,'</span>');
        html = html.replace(/\bstrong: ?/g,'<strong>');
        html = html.replace(/ ?!strong/g,'</strong>');
        html = html.replace(/\bcss: ?/g,'<style>');
        html = html.replace(/ ?!css/g,'</style>');
        html = html.replace(/\bsub: ?/g,'<sub>');
        html = html.replace(/ ?!sub/g,'</sub>');
        html = html.replace(/\bsummary: ?/g,'<summary>');
        html = html.replace(/ ?!summary/g,'</summary>');
        html = html.replace(/\bsup: ?/g,'<sup>');
        html = html.replace(/ ?!sup/g,'</sup>');
        html = html.replace(/\btable: ?/g,'<table>');
        html = html.replace(/ ?!table/g,'</table>');
        html = html.replace(/\btbody: ?/g,'<tbody>');
        html = html.replace(/ ?!tbody/g,'</tbody>');
        html = html.replace(/\btd: ?/g,'<td>');
        html = html.replace(/ ?!td/g,'</td>');
        html = html.replace(/\btextarea: ?/g,'<textarea>');
        html = html.replace(/ ?!textarea/g,'</textarea>');
        html = html.replace(/\btfoot: ?/g,'<tfoot>');
        html = html.replace(/ ?!tfoot/g,'</tfoot>');
        html = html.replace(/\bth: ?/g,'<th>');
        html = html.replace(/ ?!th/g,'</th>');
        html = html.replace(/\bthead: ?/g,'<thead>');
        html = html.replace(/ ?!thead/g,'</thead>');
        html = html.replace(/\btime: ?/g,'<time>');
        html = html.replace(/ ?!time/g,'</time>');
        html = html.replace(/\btr: ?/g,'<tr>');
        html = html.replace(/ ?!tr/g,'</tr>');
        html = html.replace(/track/g,'<track>');
        html = html.replace(/\bul: ?/g,'<ul>');
        html = html.replace(/ ?!ul/g,'</ul>');
        //html = html.replace(/\bvar: ?/g,'<var>');
        //html = html.replace(/ ?!var/g,'</var>');
        html = html.replace(/\bvideo: ?/g,'<video>');
        html = html.replace(/ ?!video/g,'</video>');
        html = html.replace(/wbr/g,'<wbr>');
        html = html.replace(/\bwrong: ?/g,'<s>');
        html = html.replace(/ ?!wrong/g,'</s>');

        code = code.split(`doc: {${old_html}}`).join(`doc: {${html}}`);
        code = code.split(`doc:{${old_html}}`).join(`doc:{${html}}`);
        return code;
    },

    attributes: function(code:string):string { /** Interpretación de atributos */
        let html:string = this.find_doc(code);
        let old_html:string = html;

        html = html.replace(/click:/g,'onclick="');
        html = html.replace(/keyup:/g,'onkeyup="');
        html = html.replace(/keydown:/g,'onkeydown="');
        html = html.replace(/"id: ?(.*?)"/g,'id="$1"');
        html = html.replace(/"css: ?(.*?)"/g,'class="$1"');
        html = html.replace(/"to: ?(.*?)"/g,'href="$1.html"');
        html = html.replace(/newtab/g,'target="_blank"');
        html = html.replace(/"name: ?(.*?)"/g,'name="$1"');
        html = html.replace(/"language: ?(.*?)"/g,'language="$1"');
        html = html.replace(/"lang: ?(.*?)"/g,'lang="$1"');
        html = html.replace(/"text: ?(.*?)"/g,'text="$1"');
        html = html.replace(/"bgcolor: ?(.*?)"/g,'bgcolor="$1"');
        html = html.replace(/"bg: ?(.*?)"/g,'background="$1"');
        html = html.replace(/"color: ?(.*?)"/g,'color="$1"');
        html = html.replace(/"size: ?(.*?)"/g,'size="$1"');
        html = html.replace(/"src: ?(.*?)"/g,'src="$1"');
        html = html.replace(/"w: ?(.*?)"/g,'width="$1"');
        html = html.replace(/"h: ?(.*?)"/g,'height="$1"');
        html = html.replace(/"name: ?(.*?)"/g,'name="$1"');
        html = html.replace(/"type: ?(.*?)"/g,'type="$1"');
        html = html.replace(/"target: ?(.*?)"/g,'target="$1"');
        html = html.replace(/"val: ?(.*?)"/g,'value="$1"');
        html = html.replace(/"border: ?(.*?)"/g,'border="$1"');
        html = html.replace(/"cpadding: ?(.*?)"/g,'cellpadding="$1"');
        html = html.replace(/"cspacing: ?(.*?)"/g,'cellspacing="$1"');
        html = html.replace(/"align: ?(.*?)"/g,'align="$1"');
        html = html.replace(/"valign: ?(.*?)"/g,'valign="$1"');
        html = html.replace(/"rspan: ?(.*?)"/g,'rowspan="$1"');
        html = html.replace(/"cspan: ?(.*?)"/g,'colspan="$1"');
        html = html.replace(/"rows: ?(.*?)"/g,'rows="$1"');
        html = html.replace(/"cols: ?(.*?)"/g,'cols="$1"');

        html = html.replace(/\ba\ ?\( ?(.*?)\)/g,'<a $1>');
        html = html.replace(/\babbr\ ?\( ?(.*?)\)/g,'<abbr $1>');
        html = html.replace(/\baddress\ ?\( ?(.*?)\)/g,'<address $1>');
        html = html.replace(/\barea\ ?\( ?(.*?)\)/g,'<area $1>');
        html = html.replace(/\barticle\ ?\( ?(.*?)\)/g,'<article $1>');
        html = html.replace(/\baside\ ?\( ?(.*?)\)/g,'<aside $1>');
        html = html.replace(/\baudio\ ?\( ?(.*?)\)/g,'<audio $1>');
        html = html.replace(/\bb\ ?\( ?(.*?)\)/g,'<b $1>');
        html = html.replace(/\bbase\ ?\( ?(.*?)\)/g,'<base $1>');
        html = html.replace(/\bbdi\ ?\( ?(.*?)\)/g,'<bdi $1>');
        html = html.replace(/\bbdo\ ?\( ?(.*?)\)/g,'<bdo $1>');
        html = html.replace(/\bquote\ ?\( ?(.*?)\)/g,'<blockquote $1>');
        html = html.replace(/\bapp\ ?\( ?(.*?)\)/g,'<body $1>');
        html = html.replace(/\bbr\ ?\( ?(.*?)\)/g,'<br $1>');
        html = html.replace(/\bbtn\ ?\( ?(.*?)\)/g,'<button $1>');
        html = html.replace(/\bcanvas\ ?\( ?(.*?)\)/g,'<canvas $1>');
        html = html.replace(/\bcaption\ ?\( ?(.*?)\)/g,'<caption $1>');
        html = html.replace(/\bcite\ ?\( ?(.*?)\)/g,'<cite $1>');
        html = html.replace(/\bcode\ ?\( ?(.*?)\)/g,'<code $1>');
        html = html.replace(/\bcol\ ?\( ?(.*?)\)/g,'<col $1>');
        html = html.replace(/\bcolgroup\ ?\( ?(.*?)\)/g,'<colgroup $1>');
        html = html.replace(/\bcommand\ ?\( ?(.*?)\)/g,'<command $1>');
        html = html.replace(/\bdatalist\ ?\( ?(.*?)\)/g,'<datalist $1>');
        html = html.replace(/\bdd\ ?\( ?(.*?)\)/g,'<dd $1>');
        html = html.replace(/\bdel\ ?\( ?(.*?)\)/g,'<del $1>');
        html = html.replace(/\bdetails\ ?\( ?(.*?)\)/g,'<details $1>');
        html = html.replace(/\bdfn\ ?\( ?(.*?)\)/g,'<dfn $1>');
        html = html.replace(/\bdialog\ ?\( ?(.*?)\)/g,'<dialog $1>');
        html = html.replace(/\bbox\ ?\( ?(.*?)\)/g,'<div $1>');
        html = html.replace(/\btemplate\ ?\( ?(.*?)\)/g,'<div $1>');
        html = html.replace(/\bdl\ ?\( ?(.*?)\)/g,'<dl $1>');
        html = html.replace(/\bdt\ ?\( ?(.*?)\)/g,'<dt $1>');
        html = html.replace(/\bem\ ?\( ?(.*?)\)/g,'<em $1>');
        html = html.replace(/\bembed\ ?\( ?(.*?)\)/g,'<embed $1>');
        html = html.replace(/\bfieldset\ ?\( ?(.*?)\)/g,'<fieldset $1>');
        html = html.replace(/\bfigcaption\ ?\( ?(.*?)\)/g,'<figcaption $1>');
        html = html.replace(/\bfigure\ ?\( ?(.*?)\)/g,'<figure $1>');
        html = html.replace(/\bform\ ?\( ?(.*?)\)/g,'<form $1>');
        html = html.replace(/\bh1\ ?\( ?(.*?)\)/g,'<h1 $1>');
        html = html.replace(/\bh2\ ?\( ?(.*?)\)/g,'<h2 $1>');
        html = html.replace(/\bh3\ ?\( ?(.*?)\)/g,'<h3 $1>');
        html = html.replace(/\bh4\ ?\( ?(.*?)\)/g,'<h4 $1>');
        html = html.replace(/\bh5\ ?\( ?(.*?)\)/g,'<h5 $1>');
        html = html.replace(/\bh6\ ?\( ?(.*?)\)/g,'<h6 $1>');
        html = html.replace(/\bhead\ ?\( ?(.*?)\)/g,'<head $1>');
        html = html.replace(/\bheader\ ?\( ?(.*?)\)/g,'<header $1>');
        html = html.replace(/\bhgroup\ ?\( ?(.*?)\)/g,'<hgroup $1>');
        html = html.replace(/\bhr\ ?\( ?(.*?)\)/g,'<hr $1>');
        html = html.replace(/\bi\ ?\( ?(.*?)\)/g,'<i $1>');
        html = html.replace(/\biframe\ ?\( ?(.*?)\)/g,'<iframe $1>');
        html = html.replace(/\binput\ ?\( ?(.*?)\)/g,'<input $1>');
        html = html.replace(/\bins\ ?\( ?(.*?)\)/g,'<ins $1>');
        html = html.replace(/\bkbd\ ?\( ?(.*?)\)/g,'<kbd $1>');
        html = html.replace(/\bkeygen\ ?\( ?(.*?)\)/g,'<keygen $1>');
        html = html.replace(/\blabel\ ?\( ?(.*?)\)/g,'<label $1>');
        html = html.replace(/\blegend\ ?\( ?(.*?)\)/g,'<legend $1>');
        html = html.replace(/\bli\ ?\( ?(.*?)\)/g,'<li $1>');
        html = html.replace(/\bresource\ ?\( ?(.*?)\)/g,'<link $1>');
        html = html.replace(/\bmap\ ?\( ?(.*?)\)/g,'<map $1>');
        html = html.replace(/\bmark\ ?\( ?(.*?)\)/g,'<mark $1>');
        html = html.replace(/\bmenu\ ?\( ?(.*?)\)/g,'<menu $1>');
        html = html.replace(/\bmeter\ ?\( ?(.*?)\)/g,'<meter $1>');
        html = html.replace(/\bnav\ ?\( ?(.*?)\)/g,'<nav $1>');
        html = html.replace(/\bnoscript\ ?\( ?(.*?)\)/g,'<noscript $1>');
        html = html.replace(/\bobject\ ?\( ?(.*?)\)/g,'<object $1>');
        html = html.replace(/\bol\ ?\( ?(.*?)\)/g,'<ol $1>');
        html = html.replace(/\boptgroup\ ?\( ?(.*?)\)/g,'<optgroup $1>');
        html = html.replace(/\boption\ ?\( ?(.*?)\)/g,'<option $1>');
        html = html.replace(/\boutput\ ?\( ?(.*?)\)/g,'<output $1>');
        html = html.replace(/\bp\ ?\( ?(.*?)\)/g,'<p $1>');
        html = html.replace(/\bpre\ ?\( ?(.*?)\)/g,'<pre $1>');
        html = html.replace(/\bprogress\ ?\( ?(.*?)\)/g,'<progress $1>');
        html = html.replace(/\bq\ ?\( ?(.*?)\)/g,'<q $1>');
        html = html.replace(/\brp\ ?\( ?(.*?)\)/g,'<rp $1>');
        html = html.replace(/\brt\ ?\( ?(.*?)\)/g,'<rt $1>');
        html = html.replace(/\bruby\ ?\( ?(.*?)\)/g,'<ruby $1>');
        html = html.replace(/\bs\ ?\( ?(.*?)\)/g,'<s $1>');
        html = html.replace(/\bsamp\ ?\( ?(.*?)\)/g,'<samp $1>');
        html = html.replace(/\bjs\ ?\( ?(.*?)\)/g,'<script $1>');
        html = html.replace(/\bsection\ ?\( ?(.*?)\)/g,'<section $1>');
        html = html.replace(/\bselect\ ?\( ?(.*?)\)/g,'<select $1>');
        html = html.replace(/\bsmall\ ?\( ?(.*?)\)/g,'<small $1>');
        html = html.replace(/\bsource\ ?\( ?(.*?)\)/g,'<source $1>');
        html = html.replace(/\bspan\ ?\( ?(.*?)\)/g,'<span $1>');
        html = html.replace(/\bstrong\ ?\( ?(.*?)\)/g,'<strong $1>');
        html = html.replace(/\bsub\ ?\( ?(.*?)\)/g,'<sub $1>');
        html = html.replace(/\bsummary\ ?\( ?(.*?)\)/g,'<summary $1>');
        html = html.replace(/\bsup\ ?\( ?(.*?)\)/g,'<sup $1>');
        html = html.replace(/\btable\ ?\( ?(.*?)\)/g,'<table $1>');
        html = html.replace(/\btbody\ ?\( ?(.*?)\)/g,'<tbody $1>');
        html = html.replace(/\btd\ ?\( ?(.*?)\)/g,'<td $1>');
        html = html.replace(/\btextarea\ ?\( ?(.*?)\)/g,'<textarea $1>');
        html = html.replace(/\btfoot\ ?\( ?(.*?)\)/g,'<tfoot $1>');
        html = html.replace(/\bth\ ?\( ?(.*?)\)/g,'<th $1>');
        html = html.replace(/\bthead\ ?\( ?(.*?)\)/g,'<thead $1>');
        html = html.replace(/\btime\ ?\( ?(.*?)\)/g,'<time $1>');
        html = html.replace(/\btitle\ ?\( ?(.*?)\)/g,'<title $1>');
        html = html.replace(/\btr\ ?\( ?(.*?)\)/g,'<tr $1>');
        html = html.replace(/\btrack\ ?\( ?(.*?)\)/g,'<track $1>');
        html = html.replace(/\bul\ ?\( ?(.*?)\)/g,'<ul $1>');
        html = html.replace(/\bvar\ ?\( ?(.*?)\)/g,'<var $1>');
        html = html.replace(/\bvideo\ ?\( ?(.*?)\)/g,'<video $1>');
        html = html.replace(/\bwbr\ ?\( ?(.*?)\)/g,'<wbr $1>');

        code = code.split(`doc: {${old_html}}`).join(`doc: {${html}}`);
        code = code.split(`doc:{${old_html}}`).join(`doc:{${html}}`);
        return code;
    },

    jscompile: function(html:string):string { /** Interpretación: { Nue } --> { JavaScript } */
        html = html.replace(/dom/g,'document');
        html = html.replace(/byId/g,'getElementById');
        html = html.replace(/byTag/g,'getElementsByTagName');
        html = html.replace(/byClass/g,'getElementsByClassName');
        html = html.replace(/allQuery/g,'querySelectorAll');
        html = html.replace(/create/g,'createElement');
        html = html.replace(/storage/g,'localStorage');

        return html;
    },

    deleteLinks: function(html:string):string { /** Eliminado de links escritos en Nue */
        if (html.indexOf('links(') != -1) {
            let links_content:string = html.split('links(').pop().split(/\)/)[0];
            let links_tag:string = `links(${links_content})`;
            html = html.split(links_tag).join('');
        }
        return html;
    },

    fixTags: function(html:string):string { /** Cerrar etiquetas sin cerrar */
        let doc:string = this.find_doc(html);
        let new_html:string = $c(doc);
        html = html.split(doc).join(new_html);
        return html;
    }
}

export {}